# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtWidgets import QLabel, QMainWindow, QApplication, QPushButton, \
QScrollBar, QFrame, QLineEdit, QSlider, QProgressBar, QDoubleSpinBox, \
QSizePolicy, QHBoxLayout
from PyQt5.QtCore import QRect, Qt, QMetaObject, QCoreApplication
from PyQt5.QtGui import QFont, QPixmap

import sys
import platform
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas

system = platform.system()

class Contrast3dAnalysisGUI(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setObjectName("3D Contrast Analysis")
        self.resize(1175, 731)

#------------------------------------------------------------------------
#------------------------------------------------------------------------
        #create feedback labels
        self.feedbackText = QLabel(self)
        self.feedbackText.setWordWrap(True)
        self.feedbackText.move(20,225)
        self.feedbackText.resize(161,47)
        self.feedbackText.setText("Input NIFTI file on left side, input folders on right side to generate NIFTI")
        self.feedbackText.setAlignment(Qt.AlignCenter)
        if system == 'Windows':
            font = QFont()
            font.setPointSize(6)
            self.feedbackText.setFont(font)

        self.totalFramesAx = QLabel(self)
        self.totalFramesAx.move(805,340)
        self.totalFramesAx.resize(31,16)
        self.totalFramesAx.setText("0")

        self.totalFramesSag = QLabel(self)
        self.totalFramesSag.move(1135,340)
        self.totalFramesSag.resize(31,16)
        self.totalFramesSag.setText("0")

        self.totalFramesCor = QLabel(self)
        self.totalFramesCor.move(1135,700)
        self.totalFramesCor.resize(31,16)
        self.totalFramesCor.setText("0")

        self.totalSlices = QLabel(self)
        self.totalSlices.move(650, 430)
        self.totalSlices.resize(31, 16)
        self.totalSlices.setText("0")

        self.curSlices = QLabel(self)
        self.curSlices.move(600, 430)
        self.curSlices.resize(31, 16)
        self.curSlices.setText("0")

        self.slicesLabel = QLabel(self)
        self.slicesLabel.setGeometry(QRect(510, 390, 251, 20))
        self.slicesLabel.setText("Current Slice:")
        self.slicesLabel.setAlignment(Qt.AlignCenter)

        self.alphaLabel = QLabel(self)
        self.alphaLabel.setGeometry(QRect(510, 510, 251, 20))
        self.alphaLabel.setText("VOI Alpha:")
        self.alphaLabel.setAlignment(Qt.AlignCenter)

        self.slicesOf = QLabel(self)
        self.slicesOf.setGeometry(QRect(630, 430, 31, 16))
        self.slicesOf.setText("of")

        self.currentFrameAx = QLabel(self)
        self.currentFrameAx.move(770,340)
        self.currentFrameAx.resize(31,16)
        self.currentFrameAx.setText("0")

        self.currentFrameSag = QLabel(self)
        self.currentFrameSag.move(1100,340)
        self.currentFrameSag.resize(31,16)
        self.currentFrameSag.setText("0")

        self.currentFrameCor = QLabel(self)
        self.currentFrameCor.move(1100,700)
        self.currentFrameCor.resize(31,16)
        self.currentFrameCor.setText("0")

        self.slicesChanger = QSlider(self)
        self.slicesChanger.move(530, 465)
        self.slicesChanger.resize(221, 32)
        self.slicesChanger.setOrientation(Qt.Horizontal)
        self.slicesChanger.setMinimum(0)
        self.slicesChanger.setDisabled(True)

        self.alphaTracker = QProgressBar(self)
        self.alphaTracker.move(510, 550)
        self.alphaTracker.resize(221, 32)
        self.alphaTracker.setMinimum(0)
        self.alphaTracker.setMaximum(255)

        self.curAlpha = QDoubleSpinBox(self)
        self.curAlpha.setFocusPolicy(Qt.StrongFocus)
        self.curAlpha.move(750, 550)
        self.curAlpha.resize(62, 22)
        self.curAlpha.setMinimum(0)
        self.curAlpha.setMaximum(255)
        self.curAlpha.setSingleStep(1)
        self.curAlpha.setDecimals(0)
        self.curAlpha.setDisabled(True)

        self.ticVarLabel = QLabel(self)
        self.ticVarLabel.setGeometry(QRect(0, 185, 221, 20))
        self.ticVarLabel.setText("TIC Variables:")
        self.ticVarLabel.setAlignment(Qt.AlignCenter)
        self.ticVarLabel.setHidden(True)

        self.ticAucLabel = QLabel(self)
        self.ticAucLabel.setGeometry(QRect(40, 210, 161, 16))
        self.ticAucLabel.setText("AUC:")
        self.ticAucLabel.setHidden(True)

        self.ticAucVal = QLabel(self)
        self.ticAucVal.setGeometry(QRect(140, 210, 100, 16))
        self.ticAucVal.setHidden(True)

        self.ticPeLabel = QLabel(self)
        self.ticPeLabel.setGeometry(QRect(40, 230, 161, 16))
        self.ticPeLabel.setText("PE:")
        self.ticPeLabel.setHidden(True)

        self.ticPeVal = QLabel(self)
        self.ticPeVal.setGeometry(QRect(140, 230, 100, 16))
        self.ticPeVal.setHidden(True)

        self.ticMttLabel = QLabel(self)
        self.ticMttLabel.setGeometry(QRect(40, 250, 161, 16))
        self.ticMttLabel.setText("MTT:")
        self.ticMttLabel.setHidden(True)

        self.ticMttVal = QLabel(self)
        self.ticMttVal.setGeometry(QRect(140, 250, 100, 16))
        self.ticMttVal.setHidden(True)

        self.ticTpLabel = QLabel(self)
        self.ticTpLabel.setGeometry(QRect(40, 270, 161, 16))
        self.ticTpLabel.setText("TP:")
        self.ticTpLabel.setHidden(True)

        self.ticTpVal = QLabel(self)
        self.ticTpVal.setGeometry(QRect(140, 270, 100, 16))
        self.ticTpVal.setHidden(True)

        self.compressLabel = QLabel(self)
        self.compressLabel.setGeometry(QRect(490, 598, 150, 15))
        self.compressLabel.setText("Compression Factor: ")
        self.compressValue = QDoubleSpinBox(self)
        self.compressValue.setFocusPolicy(Qt.StrongFocus)
        self.compressValue.setGeometry(QRect(660, 595, 62, 22))
        self.compressValue.setValue(24.09)
        self.compressValue.setAlignment(Qt.AlignRight)

        self.windowHeightLabel = QLabel(self)
        self.windowHeightLabel.setGeometry(QRect(490, 628, 150, 15))
        self.windowHeightLabel.setText("Voxel Height (mm): ")

        self.windowHeightValue = QDoubleSpinBox(self)
        self.windowHeightValue.setFocusPolicy(Qt.StrongFocus)
        self.windowHeightValue.setGeometry(QRect(660, 625, 62, 22))
        self.windowHeightValue.setValue(6.8)
        self.windowHeightValue.setAlignment(Qt.AlignRight)

        self.windowWidthLabel = QLabel(self)
        self.windowWidthLabel.setGeometry(QRect(490, 658, 150, 15))
        self.windowWidthLabel.setText("Voxel Width (mm): ")

        self.windowWidthValue = QDoubleSpinBox(self)
        self.windowWidthValue.setFocusPolicy(Qt.StrongFocus)
        self.windowWidthValue.setGeometry(QRect(660, 655, 62, 22))
        self.windowWidthValue.setValue(8.8)
        self.windowWidthValue.setAlignment(Qt.AlignRight)

        self.windowDepthLabel = QLabel(self)
        self.windowDepthLabel.setGeometry(QRect(490, 688, 150, 15))
        self.windowDepthLabel.setText("Voxel Depth (mm): ")

        self.windowDepthValue = QDoubleSpinBox(self)
        self.windowDepthValue.setGeometry(QRect(660, 685, 62, 22))
        self.windowDepthValue.setValue(5)
        self.windowDepthValue.setAlignment(Qt.AlignRight)
        self.windowDepthValue.setFocusPolicy(Qt.StrongFocus)

        self.ticDisplay = QFrame(self)
        self.ticDisplay.setGeometry(QRect(0, 580, 461, 151))

        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ticDisplay.sizePolicy().hasHeightForWidth())

        self.ticDisplay.setSizePolicy(sizePolicy)
        self.ticDisplay.setFrameShape(QFrame.StyledPanel)
        self.ticDisplay.setFrameShadow(QFrame.Raised)

        self.horizLayout = QHBoxLayout(self.ticDisplay)
        self.fig = plt.figure()
        self.canvas = FigureCanvas(self.fig)
        self.horizLayout.addWidget(self.canvas)
        self.canvas.draw()

        self.legend = QFrame(self)
        self.legend.setGeometry(QRect(715, 580, 100, 150))
        self.legend.setSizePolicy(sizePolicy)
        self.legend.setFrameShape(QFrame.StyledPanel)
        self.legend.setFrameShadow(QFrame.Raised)
        self.legend.setHidden(True)

        self.figLeg = plt.figure()
        self.canvasLeg = FigureCanvas(self.figLeg)
        self.horizLayoutLeg = QHBoxLayout(self.legend)
        self.horizLayoutLeg.addWidget(self.canvasLeg)
        self.canvasLeg.draw()

        self.niftiLabel = QLabel(self)
        self.niftiLabel.setGeometry(QRect(10, 15, 181, 16))
        self.niftiLabel.setTextInteractionFlags(Qt.NoTextInteraction)
        self.niftiLabel.setAlignment(Qt.AlignCenter)
        self.niftiLabel.setObjectName("niftiLabel")

        self.chooseFileButton = QPushButton(self)
        self.chooseFileButton.setGeometry(QRect(0, 80, 113, 32))
        self.chooseFileButton.setObjectName("chooseFileButton")

        self.openIMGButton = QPushButton(self)
        self.openIMGButton.setGeometry(QRect(50, 120, 111, 32))
        self.openIMGButton.setObjectName("openIMGButton")

        self.instrFunctLabel = QLabel(self)
        self.instrFunctLabel.setGeometry(QRect(20, 300, 331, 16))
        self.instrFunctLabel.setTextInteractionFlags(Qt.NoTextInteraction)
        self.instrFunctLabel.setObjectName("instrFunctLabel")

        self.drawPolygonButton = QPushButton(self)
        self.drawPolygonButton.setGeometry(QRect(20, 330, 121, 32))
        self.drawPolygonButton.setObjectName("drawPolygonButton")

        self.aucParamapButton = QPushButton(self)
        self.aucParamapButton.setGeometry(QRect(0, 410, 115, 31))
        self.aucParamapButton.setObjectName("aucParamapButton")
        self.aucParamapButton.setHidden(True)

        self.displayTICButton = QPushButton(self)
        self.displayTICButton.setGeometry(QRect(340, 260, 211, 32))
        self.displayTICButton.setObjectName("displayTICButton")
        self.displayTICButton.setHidden(True)

        self.axialTextLabel = QLabel(self)
        self.axialTextLabel.setGeometry(QRect(480, 10, 331, 16))
        self.axialTextLabel.setAlignment(Qt.AlignCenter)
        self.axialTextLabel.setTextInteractionFlags(Qt.NoTextInteraction)
        self.axialTextLabel.setObjectName("axialTextLabel")
        self.sagTextLabel = QLabel(self)
        self.sagTextLabel.setGeometry(QRect(840, 10, 331, 16))
        self.sagTextLabel.setAlignment(Qt.AlignCenter)
        self.sagTextLabel.setTextInteractionFlags(Qt.NoTextInteraction)
        self.sagTextLabel.setObjectName("sagTextLabel")
        self.corTextLabel = QLabel(self)
        self.corTextLabel.setGeometry(QRect(820, 370, 331, 16))
        self.corTextLabel.setAlignment(Qt.AlignCenter)
        self.corTextLabel.setTextInteractionFlags(Qt.NoTextInteraction)
        self.corTextLabel.setObjectName("corTextLabel")

        self.axialPlane = QLabel(self)
        self.axialPlane.setGeometry(QRect(479, 30, 331, 311))
        self.axialPlane.setFrameShape(QFrame.Box)
        self.axialPlane.setFrameShadow(QFrame.Sunken)
        self.axialPlane.setText("")
        self.axialPlane.setObjectName("axialPlane")

        self.sagPlane = QLabel(self)
        self.sagPlane.setGeometry(QRect(820, 30, 331, 311))
        self.sagPlane.setFrameShape(QFrame.Box)
        self.sagPlane.setFrameShadow(QFrame.Sunken)
        self.sagPlane.setText("")
        self.sagPlane.setObjectName("sagPlane")

        self.corPlane = QLabel(self)
        self.corPlane.setGeometry(QRect(820, 390, 331, 311))
        self.corPlane.setFrameShape(QFrame.Box)
        self.corPlane.setFrameShadow(QFrame.Sunken)
        self.corPlane.setText("")
        self.corPlane.setObjectName("corPlane")

        self.line1 = QFrame(self)
        self.line1.setGeometry(QRect(0, 280, 461, 21))
        self.line1.setFrameShape(QFrame.HLine)
        self.line1.setFrameShadow(QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.line2 = QFrame(self)
        self.line2.setGeometry(QRect(440, 0, 41, 731))
        self.line2.setFrameShape(QFrame.VLine)
        self.line2.setFrameShadow(QFrame.Sunken)
        self.line2.setObjectName("line2")

        self.interpolateVOIButton = QPushButton(self)
        self.interpolateVOIButton.setGeometry(QRect(20, 370, 201, 32))
        self.interpolateVOIButton.setObjectName("interpolateVOI")

        self.undoLastPtButton = QPushButton(self)
        self.undoLastPtButton.setGeometry(QRect(150, 330, 161, 32))
        self.undoLastPtButton.setObjectName("undoLastPtButton")

        self.clearFileButton = QPushButton(self)
        self.clearFileButton.setGeometry(QRect(110, 80, 113, 32))
        self.clearFileButton.setObjectName("clearFileButton")

        self.acceptPolygonButton = QPushButton(self)
        self.acceptPolygonButton.setGeometry(QRect(320, 330, 131, 32))
        self.acceptPolygonButton.setObjectName("acceptPolygonButton")

        self.ofTextAx = QLabel(self)
        self.ofTextAx.setGeometry(QRect(790, 340, 31, 16))
        self.ofTextAx.setObjectName("label")
        self.ofTextSag = QLabel(self)
        self.ofTextSag.setGeometry(QRect(1120, 340, 31, 16))
        self.ofTextSag.setObjectName("label_2")
        self.ofTextCor = QLabel(self)
        self.ofTextCor.setGeometry(QRect(1120, 700, 31, 16))
        self.ofTextCor.setObjectName("label_3")

        self.expandAxialButton = QPushButton(self)
        self.expandAxialButton.setGeometry(QRect(0, 500, 151, 31))
        self.expandAxialButton.setObjectName("expandAxial")
        self.expandSagButton = QPushButton(self)
        self.expandSagButton.setGeometry(QRect(150, 500, 151, 31))
        self.expandSagButton.setObjectName("expandSagittal")
        self.expandCorButton = QPushButton(self)
        self.expandCorButton.setGeometry(QRect(300, 500, 151, 31))
        self.expandCorButton.setObjectName("expandCoronal")

        self.line1_2 = QFrame(self)
        self.line1_2.setGeometry(QRect(0, 450, 461, 16))
        self.line1_2.setFrameShape(QFrame.HLine)
        self.line1_2.setFrameShadow(QFrame.Sunken)
        self.line1_2.setObjectName("line1_2")

        self.closeExpandButton = QPushButton(self)
        self.closeExpandButton.setGeometry(QRect(130, 540, 191, 32))
        self.closeExpandButton.setObjectName("closeExpand")

        self.peParamapButton = QPushButton(self)
        self.peParamapButton.setGeometry(QRect(118, 410, 115, 31))
        self.peParamapButton.setObjectName("peParamapButton")
        self.peParamapButton.setHidden(True)

        self.tpParamapButton = QPushButton(self)
        self.tpParamapButton.setGeometry(QRect(230, 410, 115, 31))
        self.tpParamapButton.setObjectName("tpParamapButton")
        self.tpParamapButton.setHidden(True)

        self.calculateParamapButton = QPushButton(self)
        self.calculateParamapButton.setText("Calculate Parametric Map")
        self.calculateParamapButton.setGeometry(QRect(135, 410, 191, 32))
        # QRect(130, 540, 191, 32)

        self.xmlLabel = QLabel(self)
        self.xmlLabel.setGeometry(QRect(240, 10, 201, 16))
        self.xmlLabel.setTextInteractionFlags(Qt.NoTextInteraction)
        self.xmlLabel.setObjectName("xmlLabel")

        self.niftiDestinationLabel = QLabel(self)
        self.niftiDestinationLabel.setGeometry(QRect(240, 110, 201, 16))
        self.niftiDestinationLabel.setTextInteractionFlags(Qt.NoTextInteraction)
        self.niftiDestinationLabel.setText("Destination for coverted nifti:")

        self.line = QFrame(self)
        self.line.setGeometry(QRect(210, 0, 31, 291))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line.setObjectName("line")

        self.chooseInputFolderButton = QPushButton(self)
        self.chooseInputFolderButton.setGeometry(QRect(230, 72, 113, 32))

        self.chooseOutputFolderButton = QPushButton(self)
        self.chooseOutputFolderButton.setGeometry(QRect(230, 175, 113, 32))

        self.clearInputFolderButton = QPushButton(self)
        self.clearInputFolderButton.setGeometry(QRect(340, 72, 113, 32))

        self.clearOutputFolderButton = QPushButton(self)
        self.clearOutputFolderButton.setGeometry(QRect(340, 175, 113, 32))

        self.instrFunctLabel_2 = QLabel(self)
        self.instrFunctLabel_2.setGeometry(QRect(20, 470, 331, 16))
        self.instrFunctLabel_2.setTextInteractionFlags(Qt.NoTextInteraction)
        self.instrFunctLabel_2.setObjectName("instrFunctLabel_2")

        self.niftiLineEdit = QLabel(self)
        self.niftiLineEdit.setGeometry(QRect(10, 40, 191, 31))
        self.niftiLineEdit.setObjectName("niftiLineEdit")
        self.niftiLineEdit.setStyleSheet("border: 1px solid black;")
        self.niftiLineEdit.setAlignment(Qt.AlignRight)

        self.xmlLineEdit = QLabel(self)
        self.xmlLineEdit.setGeometry(QRect(240, 40, 191, 31))
        self.xmlLineEdit.setObjectName("xmlLineEdit")
        self.xmlLineEdit.setStyleSheet("border: 1px solid black;")
        self.xmlLineEdit.setAlignment(Qt.AlignRight)

        self.niftiDestinationLineEdit = QLabel(self)
        self.niftiDestinationLineEdit.setGeometry(QRect(240, 138, 191, 31))
        self.niftiDestinationLineEdit.setStyleSheet("border: 1px solid black;")
        self.niftiDestinationLineEdit.setAlignment(Qt.AlignRight)

        self.convertXmlButton = QPushButton(self)
        self.convertXmlButton.setGeometry(QRect(240, 235, 201, 32))
        self.convertXmlButton.setObjectName("convertXmlButton")

        self.saveBeamshapeMaskButton = QPushButton(self)
        self.saveBeamshapeMaskButton.setGeometry(QRect(260, 200, 171, 32))
        self.saveBeamshapeMaskButton.setObjectName("saveBeamshapeMaskButton")
        self.saveBeamshapeMaskButton.setHidden(True)

        self.saveMipMaskButton = QPushButton(self)
        self.saveMipMaskButton.setGeometry(QRect(260, 240, 171, 32))
        self.saveMipMaskButton.setObjectName("saveMipMaskButton")
        self.saveMipMaskButton.setHidden(True)

        self.feedbackLabel = QLabel(self)
        self.feedbackLabel.setGeometry(QRect(10, 190, 161, 16))
        self.feedbackLabel.setObjectName("feedbackLabel")
        self.line_2 = QFrame(self)
        self.line_2.setGeometry(QRect(0, 170, 221, 16))
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.feedbackScrollBar = QScrollBar(self)
        self.feedbackScrollBar.setGeometry(QRect(200, 210, 20, 71))
        self.feedbackScrollBar.setOrientation(Qt.Vertical)
        self.feedbackScrollBar.setObjectName("feedbackScrollBar")
        self.feedbackScrollBar.setHidden(True)

        self.computeTICButton = QPushButton(self)
        self.computeTICButton.setGeometry(QRect(230, 370, 221, 32))
        self.computeTICButton.setObjectName("computeTICButton")

        self.undoLastROIButton = QPushButton(self)
        self.undoLastROIButton.setGeometry(QRect(320, 330, 121, 32))
        self.undoLastROIButton.setObjectName("undoLastROI")
        self.undoLastROIButton.setHidden(True)

        self.interpolateBetweenMasksButton = QPushButton(self)
        self.interpolateBetweenMasksButton.setGeometry(QRect(360, 280, 201, 32))
        self.interpolateBetweenMasksButton.setObjectName("interpolateButton")
        self.interpolateBetweenMasksButton.setHidden(True)

        self.saveSegImgAx = QPushButton(self)
        self.saveSegImgAx.setGeometry(QRect(470, 340, 211, 32))
        self.saveSegImgAx.setObjectName("saveSegImgAx")
        self.saveSegImgAx.setHidden(True)

        self.saveSegImgSag = QPushButton(self)
        self.saveSegImgSag.setGeometry(QRect(830, 340, 211, 32))
        self.saveSegImgSag.setObjectName("savSegImgSag")
        self.saveSegImgSag.setHidden(True)

        self.saveSegImgCor = QPushButton(self)
        self.saveSegImgCor.setGeometry(QRect(830, 700, 211, 32))
        self.saveSegImgCor.setObjectName("saveSegImgCor")
        self.saveSegImgCor.setHidden(True)

        self.mttParamapButton = QPushButton(self)
        self.mttParamapButton.setGeometry(QRect(340, 410, 115, 32))
        self.mttParamapButton.setObjectName("mttParamapButton")
        self.mttParamapButton.setHidden(True)

        self.maskLayerAx = QLabel(self)
        self.maskLayerAx.setGeometry(QRect(479, 30 ,331, 311))

        self.maskLayerSag = QLabel(self)
        self.maskLayerSag.setGeometry(QRect(820, 30 ,331, 311))

        self.maskLayerCor = QLabel(self)
        self.maskLayerCor.setGeometry(QRect(820, 390, 331, 311))
        
        self.setMouseTracking(True)

        self.axCoverPixmap = QPixmap(331, 311)
        self.axCoverPixmap.fill(Qt.transparent)
        self.axCoverLabel = QLabel(self)
        self.axCoverLabel.setGeometry(QRect(479, 30, 331, 311))
        self.axCoverLabel.setMouseTracking(True)
        self.axCoverLabel.setPixmap(self.axCoverPixmap)

        self.inputTextPath=""

        self.sagCoverPixmap = QPixmap(331, 311)
        self.sagCoverPixmap.fill(Qt.transparent)
        self.sagCoverLabel = QLabel(self)
        self.sagCoverLabel.setGeometry(QRect(820, 30 ,331, 311))
        self.sagCoverLabel.setMouseTracking(True)
        self.sagCoverLabel.setPixmap(self.sagCoverPixmap)

        self.corCoverPixmap = QPixmap(331, 311)
        self.corCoverPixmap.fill(Qt.transparent)
        self.corCoverLabel = QLabel(self)
        self.corCoverLabel.setGeometry(QRect(820, 390, 331, 311))
        self.corCoverLabel.setMouseTracking(True)
        self.corCoverLabel.setPixmap(self.corCoverPixmap)

        self.line1_3 = QFrame(self)
        self.line1_3.setGeometry(QRect(0, 570, 461, 16))
        self.line1_3.setFrameShape(QFrame.HLine)
        self.line1_3.setFrameShadow(QFrame.Sunken)
        self.line1_3.setObjectName("line1_3")

        self.xCur = 0
        self.yCur = 0
        self.imagesOpened = False
        self.voiComputed = False
        self.scrolling = False
        self.curROIDrawn = True
        self.ticComputed = False
        self.id = 0
        self.curSlice = 0
        self.pointsPlotted = []
        self.curPointsPlottedX = []
        self.curPointsPlottedY = []
        self.planesDrawn = []
        self.painted = "none"

        self.retranslateUi(self)
        QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, roughGUI):
        _translate = QCoreApplication.translate
        roughGUI.setWindowTitle(_translate("3D Contrast Analysis", "3D Contrast Analysis"))
        self.niftiLabel.setText(_translate("3D Contrast Analysis", "NIfTI format, input path to file:"))
        self.chooseFileButton.setText(_translate("3D Contrast Analysis", "Choose File"))
        self.openIMGButton.setText(_translate("3D Contrast Analysis", "Open Image"))
        self.instrFunctLabel.setText(_translate("3D Contrast Analysis", "Functions to perform once image is loaded:"))
        self.drawPolygonButton.setText(_translate("3D Contrast Analysis", "Draw ROI"))
        self.aucParamapButton.setText(_translate("3D Contrast Analysis", "AUC"))
        self.displayTICButton.setText(_translate("3D Contrast Analysis", "Display Time Intensity Curve"))
        self.axialTextLabel.setText(_translate("3D Contrast Analysis", "Axial Plane"))
        self.sagTextLabel.setText(_translate("3D Contrast Analysis", "Sagittal Plane"))
        self.corTextLabel.setText(_translate("3D Contrast Analysis", "Coronal Plane"))
        self.interpolateVOIButton.setText(_translate("3D Contrast Analysis", "Interpolate VOI"))
        self.undoLastPtButton.setText(_translate("3D Contrast Analysis", "Undo Last Point"))
        self.clearFileButton.setText(_translate("3D Contrast Analysis", "Clear Path"))
        self.acceptPolygonButton.setText(_translate("3D Contrast Analysis", "Accept ROI"))
        self.ofTextAx.setText(_translate("3D Contrast Analysis", "of"))
        self.ofTextSag.setText(_translate("3D Contrast Analysis", "of"))
        self.ofTextCor.setText(_translate("3D Contrast Analysis", "of"))
        self.expandAxialButton.setText(_translate("3D Contrast Analysis", "Expand Ax.  Image"))
        self.expandSagButton.setText(_translate("3D Contrast Analysis", "Expand Sag.  Image"))
        self.expandCorButton.setText(_translate("3D Contrast Analysis", "Expand Cor.  Image"))
        self.closeExpandButton.setText(_translate("3D Contrast Analysis", "Close Expanded Image"))
        self.peParamapButton.setText(_translate("3D Contrast Analysis", "PE"))
        self.tpParamapButton.setText(_translate("3D Contrast Analysis", "TP"))
        self.xmlLabel.setText(_translate("3D Contrast Analysis", "XML format, input path to folder:"))
        self.chooseInputFolderButton.setText(_translate("3D Contrast Analysis", "Choose Folder"))
        self.chooseOutputFolderButton.setText(_translate("3D Contrast Analysis", "Choose Folder"))
        self.clearInputFolderButton.setText(_translate("3D Contrast Analysis", "Clear Path"))
        self.clearOutputFolderButton.setText(_translate("3D Contrast Analysis", "Clear Path"))
        self.instrFunctLabel_2.setText(_translate("3D Contrast Analysis", "Extra Display Functions:"))
        self.convertXmlButton.setText(_translate("3D Contrast Analysis", "Convert XML/Raw to .nii.gz"))
        self.saveBeamshapeMaskButton.setText(_translate("3D Contrast Analysis", "Save Beamshape Mask"))
        self.saveMipMaskButton.setText(_translate("3D Contrast Analysis", "Save MIP Mask"))
        self.feedbackLabel.setText(_translate("3D Contrast Analysis", "Feedback:"))
        self.computeTICButton.setText(_translate("3D Contrast Analysis", "Compute TIC"))
        self.undoLastROIButton.setText(_translate("3D Contrast Analysis", "Undo Last ROI"))
        self.interpolateBetweenMasksButton.setText(_translate("3D Contrast Analysis", "Interpolate Between Masks"))
        self.saveSegImgAx.setText(_translate("3D Contrast Analysis", "Save Segmentation Image"))
        self.saveSegImgSag.setText(_translate("3D Contrast Analysis", "Save Segmentation Image"))
        self.saveSegImgCor.setText(_translate("3D Contrast Analysis", "Save Segmentation Image"))
        self.mttParamapButton.setText(_translate("3D Contrast Analysis", "MTT"))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ui = Contrast3dAnalysisGUI()
    ui.show()
    sys.exit(app.exec_())
